server.port: 8100

spring:
  application:
    name: productservice
  docker.compose.lifecycle-management: start_only
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:8101/productservice
    username: haisia
    password: test@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  # https://docs.temporal.io/develop/java/spring-boot-integration
#  temporal:
#    connection:
#      target: localhost:7233
#    workers:
#      - task-queue: trade-task-queue
#        name: product-worker
#        activity-beans:
#          - productActivityImpl

jwt:
  secret: thisisjwttokensecretkeythisisjwttokensecretkeythisisjwttokensecretkeythisisjwttokensecretkey
  access-token:
    validity-second: 3600
  refresh-token:
    validity-second: 86400

kafka:
  bootstrap-servers: localhost:9092